### PR TITLE
Mobile update

### LINKED ISSUE #249: Homepage mobile view too wide and not responsive
**Describe the bug**
- [x] You can scroll to the right unnaturally
- [x] The center boxes do not rearrange to be on top of each other, leading to a weird look

**To Reproduce**
1. Visit the homepage on a mobile device

**Expected behavior**
A good looking mobile version

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by annieshi6**
### Description of change(s), including why:

- removed header title bc of redundancy and looks bad on mobile
- added titles to box of pages that seem to require it, didn't add it to pages where it seemed unnecessary (some pages are obvious/don't need it, or are hard to get to without knowing purpose of the page, etc)
- formatting for mobile, used like 5-6 different breakpoints chosen from inspect element devices view and other sources
- cleaned up css for question component and styled to better fit the theme
- removed all usage of btn css class (i assume part of mdbreact?) bc the button class pretty much overwrote the whole thing anyway and some of it was causing button shadows on focus/active which was just not worth overwriting
- added thin border to dropdown to distinguish from box content when it overlaps
- selection styling bc i develop on ubuntu and the orange on purple is ~nasty~ unappealing

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #249 #198 

### Screenshots (if frontend change) of before and after:

too many you can probably just view the dev link and use inspect element devices view to play w different sizes

### CODE REVIEW

File: PollBuddy-Server/frontend/src/App.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ export default class App extends React.Component {
 
         <MDBContainer id="wrapper">
 
-          <Header title={this.state.pageTitle} userInfo={this.state.userInfo} />
+          <Header />
```
Comment (hbh7) [inline PollBuddy-Server/frontend/src/App.js:62]: I think we'll need the userInfo passed like that for the dropdown to show relevant fields (when that works) but I could be wrong.

**Review by hbh7 — CHANGES_REQUESTED** [review]
Great! I checked out a few pages on the dev link and it definitely seems to work a lot better on "mobile". I left one comment that I wasn't sure about. Also, can you merge frontend back into here again so Neha's changes work with this and have no merge conflicts? Thanks :)

**Review by hbh7 — APPROVED** [review]
Awesome :D
